---
name: Cribl Edge
version: latest
slug: cribl-edge
description: Cribl Edge add-on for logging to Cribl Stream
init: false
arch:
  - aarch64
  - amd64
  - i386
image: cribl/cribl
environment: 
  - CRIBL_DIST_MODE: "managed-edge"
  - CRIBL_DIST_MASTER_URL: "tcp://criblmaster@192.168.60.115:4200"
  - CRIBL_EDGE: "1"
ports:
  9420/tcp: 9420
  9000/tcp: 9000
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
