---
name: Cribl Edge
version: latest
slug: cribl-edge
description: Cribl Edge add-on for logging to Cribl Stream
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: cribl/cribl
options:
  log_level: info
  seconds_between_quotes: 5
  token: null
  edge_leader: null
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
